### ISSUE TITLE
Add tutorial of calculating MW extinction

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-analysis#121]
Add a tutorial demonstrating how to calculate extinction for DC2.

**Comment by sschmidt23** [comment]
I added a branch with my quick stab at a tutorial, it takes a while to render as I had a FoF match to the truth extragalactic catalog to make some histograms (I also got lazy and cut and pasted each band at the bottom instead of doing it in a loop).  If someone has time, see if that seems like overkill, and also see if the way of fetching the bandpasses and such is parsable by a potential tutorial reader.
Notebook is in u/sschmidt23/mwdust branch:
https://github.com/LSSTDESC/DC2-analysis/blob/u/sschmidt23/mwdust/contributed/Deredden_MW_dust.ipynb

**Comment by sschmidt23** [comment]
I made a new, more simple notebook using the `dustmaps` package that Heather helpfully added to the desc-python-dev kernel.  It's very simple, but I think it's a nice illustration of how to deredden.

**Comment by yymao** [comment]
#137 was not correctly merged into master. Reopen.
