### ISSUE TITLE
Move tutorial notebooks from DC2-production to here and impose a consistent naming scheme

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#2]
At title, we can now move the tutorial notebooks within [DC2-production/Notebooks](https://github.com/LSSTDESC/DC2-production/tree/master/Notebooks). While we are moving the notebooks, we can rename them to have a more consistent naming scheme? 

Anyone has strong opinion on how to name these tutorial notebooks? @wmwv @fjaviersanchez @EiffL @jchiang87 @danielsf @evevkovacs?

**Comment by jchiang87** [comment]
My only request is that we use underscores instead of spaces in the names.

**Comment by yymao** [comment]
Maybe this is part of #1? @rmandelb Do you want to keep the tasks in #1 as to-do's or separate issues?

**Comment by rmandelb** [comment]
My main purpose in creating #1 was to quickly collect a few quick thoughts on things we need for basic functioning of the repo. For example, I presume that the default LICENSE choice will be the same as for DC2-production and might not require a separate discussion.  But if the tasks require any non-trivial discussion, it's probably better to split them off from #1 into separate issues like this one (so that #1 doesn't have to include a bunch of distinct conversations). 

Also, ditto what Jim said.  :)

My feeling is that the notebook naming scheme doesn't otherwise matter *too* much, though it might be nice if the README table can clearly specify what data products the notebook works with.  That's the kind of thing people might want to know (find all notebook that use the coadds or the individual visits or the extragalactic catalog) and it can be annoying to get all that into the name if it's a notebook that analyzes multiple things, so having it in the table might help.

**Comment by yymao** [comment]
One issue we have with the current names is that one cannot really tell which notebook is which because the filenames are too long and the important part is cut off in the default view: https://github.com/LSSTDESC/DC2-production/tree/master/Notebooks 

Agree that the table in the README can/should contain more information. Some of those information are probably in the [Confluence DC2 Data Product Overview page](https://confluence.slac.stanford.edu/x/oJgHDg) and we ~are too lazy to~ forget to reproduce them in the README.

**Comment by drphilmarshall** [comment]
Let's avoid white space and colons in file names as well while we're at it!
:-)

**Comment by yymao** [comment]
OK, here's my proposed names for all tutorial notebooks. The order is the same as listed [in this table](https://github.com/LSSTDESC/DC2-production/tree/master/Notebooks#dc2-notebooks). 

Please comment (or give a thumbs-up if you think the naming scheme is good). Thanks! (@wmwv @jchiang87 @EiffL @fjaviersanchez @danielsf @evevkovacs @rmandelb @drphilmarshall)

- `object_gcr_1_intro`
- `object_gcr_2_lensing_cuts`
- `object_gcr_3_challenges`
- `object_pandas_stellar_locus`
- `dm_butler_lensing_cuts`
- `dm_butler_postage_stamps`
- `dm_butler_skymap`
- `matching_stack`
- `matching_fof`
- `truth_gcr_intro`
- `protodc2_gcr_redshift_dist`
- `protodc2_gcr_hod`
- `protodc2_gcr_mass_relations`
- `protodc2_gcr_cluster_colors`
- `protodc2_gcr_cluster_members`

**Comment by rmandelb** [comment]
Are the last 5 of these really only going to be useful for protoDC2?  Or is that just how they are set up right now?  If they will be useful for cosmoDC2 eventually without having to be rewritten then perhaps the name could be more general, like `extragalactic`?

**Comment by yymao** [comment]
@rmandelb yes, you are right. I updated my comment above. Thanks!

**Comment by EiffL** [comment]
it looks good to me @yymao
