### ISSUE TITLE
instruction for DC2 users to contribute their code/notebooks

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#3]
One of main purposes of this repo is to encourage DC2 users to share their code/notebooks that may not belong to a standalone repo with the broader audience. 

Before we can write down the instruction, there's some questions we need to first answer. 

### directory structure
The simplest thing we can do is having a `contributed` directory and then ask people to upload their notebooks/code into it. 

Or we can have the `contributed/<user>` structure. For example, I can upload my notebook to `contributed/yymao`. 

Or we can use data type as subdir, like `contributed/truth`. Though some notebooks may not be easy to classified with one data type. 

Or we can use WG/TF as subdir, like `contributed/WL`. Again, some notebooks may not be easy to classified with one WG/TF. 

Or other subdirectory structure. 

### push to master vs. push to branch and then PR
Another question is whether we should ask contributors to directly push to master or push to branch and then PR. The latter protects the master branch but the former lowers the bar to contribute. If we decide to using branch+PR, we also need to decide what level of review do we need. For example, we can approve all PRs as long as they follow the directory structure that we recommend. Or we can have more substantial review.

**Comment by jchiang87** [comment]
Some combination of `contributed/<data type>` and `contributed/<WG/TF>` could work well and cover any likely type of contribution.  I think it is always advisable to have contributions go through the branch+PR process since it helps safeguard against someone accidentally pushing changes to existing code that they did not intend to touch.  The classification of the subdir could also be discussed and sorted out in the PR.

**Comment by rmandelb** [comment]
I agree with Jim; I would rather protect the master branch and have contributions go through the branch+PR process.  In fact, I will go protect the master branch now (we can always remove the protection later if there is a strong agreement that we should do so, but I think a protected master branch is a reasonable default for any repo with multiple contributors to code).  To ensure the bar to contribute is not too high, we can avoid making the review process onerous. 

Since some notebooks will most easily be classified based on data type - like they do a lot of things to demonstrate use of that data type - and others based on science, I agree we should have a mix of `contributed/<data type>` and `contributed/<WG/TF>`.  We can simply ask people to look at the existing contribution types to classify theirs before creating something new (and move things around during the review if needed).

**Comment by yymao** [comment]
(Removing proposer's hat) I agree with both of you too. If there's no further comments from other people, what we need to do is to write this up. 

Since we are going with branch+PR approach, we will need some step-by-step instruction to lower the bar for contribution. I wrote [some git instructions for gcr-catalogs](https://github.com/LSSTDESC/gcr-catalogs/blob/master/CONTRIBUTING.md#contribute-to-gcrcatalogs) that people seem to find useful. (Note that if we are granting people write access we can change the first point to new branch rather than fork.)

**Comment by yymao** [comment]
One question comes to me when I am thinking about the instruction --- 

Regarding the contributed notebooks, should we ask the contributors to clear all notebook outputs before they push their notebooks to this repo? 

And if so, should we set up @drphilmarshall's auto rendering script for the contributed notebooks as well?

**Comment by yymao** [comment]
Wouldn't it be good to get this ready to be announced on the DC2 telecon this Friday, or is it too hurried @katrinheitmann? If needed I can set some time Thursday afternoon to help setting up this repo after the questions here are discussed in the Data Access telecon.

**Comment by katrinheitmann** [comment]
I think it would be good to announce this on Friday. It can always be emphasized that it's still under construction. How about I start a slide deck "general update" and you and/or Rachel can say a few words? Thanks!

**Comment by yymao** [comment]
Answers to questions above (as discussed in the Data Access telecon):

- For now, ask contributors to put their notebooks/code under `contributed`. We can worry about finer structures when we have more than ~10 notebooks.
- Ask contributors to request write access, so that they can open new branches when contributing.
- Ask contributors to clear notebook output before commit.
- Ask contributors to use branch-PR workflow, with a minimal, low-bar review process.
- Consider providing Phil's rendering service in `contributed` as well.

As all the questions are now answered. I'll create `contributed/README.md` to detail the instruction there.

**Comment by drphilmarshall** [comment]
I think it'll be useful having the contributed notebooks rendered as well - as long as the folder has a README.rst table like the main one, we should be able to make the script work on this as well pretty easily, I'm happy to set that up.

**Comment by jchiang87** [comment]
We might want to provide a link or two in one of our README docs to other notebook repositories that contributors may find helpful for their own work.  A couple that come to mind are
https://github.com/lsst-com/notebooks
https://github.com/lsst-dm-tutorial/lsst2017

**Comment by yymao** [comment]
@jchiang87 those links are useful, thanks! I wonder if it's more suitable for them to go to `tutorials/README.md`?

**Comment by yymao** [comment]
@drphilmarshall, in fact, I was going to suggest that we change the way `beavis-ci.sh` works. I think it should create the `README.md` rather than reading it in, so that we don't need to ask every contributor to to touch the README file. (It would have also save one hour of my time change tutorials/README.md`) 

So the idea is to push script-generated README to the `rendered` branch, and in the README in master, we just have a link to the script-generated README. What do you think, @drphilmarshall?

If you think that's a good idea, can you open an issue and assign yourself or me, depending on your time?

**Comment by drphilmarshall** [comment]
I think this is a good idea - certainly editing the README is fiddly, and this approach would remove that burden on the user. What it does mean, though, is that the list of notebooks to be tested has to be passed in some other way. The default could be that all the notebooks in the folder are run: this was the original beavis scheme, but I changed it because it looked as though the DC2 folder had some notebooks in it that should not be expected to just run. I think as long as we are happy with existence-in-folder being the trigger for CIT then we should go ahead with auto-generating the README file. Also, I will agree here and also elsewhere that beavis-ci should live in its own repo - I think we should make that jump first, and then issue improvements. After merging #10 , that is...
