### ISSUE TITLE
Releasing a python DESC + (Py)Spark kernel for JupyterLab at NERSC

### ISSUE THREAD

**Issue by JulienPeloton** [LSSTDESC/DC2-analysis#33]
### Current status

There is currently a few kernels available by default for DESC users at NERSC (`desc-python`, `desc-stack`, …) but none can be used to run Apache Spark. For this we would need to slightly modify the kernel (not just adding one more library). 

In [LSSTDESC/desc-spark](https://github.com/LSSTDESC/desc-spark), I put the recipe to produce manually a `desc-python` + Apache Spark. It starts by following the `desc-python` kernel (by calling `/global/common/software/lsst/common/miniconda/kernels/python.sh`) and then set up paths such that Apache Spark can be used.

### Proposal

I propose to release a new kernel for DESC members: `desc-python-pyspark`.

It would include completely the base kernel (`desc-python`), plus the Spark environment set.
Later, we could think having the `desc-stack-pyspark` as well (but that needs to be tested).

@yymao @heather999 @djbard  @plaszczy  If you are OK with this proposal, I can basically add a new entry at `/global/common/software/lsst/common/miniconda/kernels`. Is there a repo for tracking that? Or it is done manually?

**Comment by yymao** [comment]
@JulienPeloton I support this proposal, with one minor comment: Can we just call this kernel `desc-pyspark`, or, even shorter, `desc-spark`? 

We don't have a repo that manage the kernels and setup scripts under `/global/common/software/lsst/common/miniconda/kernels`, but I think it's a good idea to create one so that we can create PRs and track issues. @heather999 what do you think? Can you create a repo for this?

**Comment by JulienPeloton** [comment]
@yymao thanks for the quick feedback. I have no objection for the name you propose - although I was just trying to mirror the current existing kernel names (anticipating that there could be a DESC Stack + Spark later on).

**Comment by heather999** [comment]
Sorry, got myself distracted.. Yes.. we should have a repo for the kernels.  
One wrinkle is that I would like to update the existing desc-python to move to miniconda 4.5.4 to catch up with the version of python used by the stack. I have an installation all set to go, but held off so far.  This might be an opportunity to make the switch so that `desc-python` and `desc-stack` are using the same underlying python packages.
First I'll make a repo..

**Comment by JulienPeloton** [comment]
@heather999 Great thanks for setting up the repo! I will add the Spark kernel asap.

**Comment by heather999** [comment]
Thanks @JulienPeloton your PR has been merged and a new jupyter-kernels-v0.0.3 has been installed at NERSC.  I briefly gave it a try and I can say the kernel loads once users run /global/common`/software/lsst/common/miniconda/kernels/setup.sh` so that the new `desc-pyspark` is added to their env.  Please give it a try too.

**Comment by JulienPeloton** [comment]
@heather999 Thanks! I gave a try, and the installation works like a charm :-)

<img width="902" alt="screenshot 2018-11-12 at 14 13 08" src="https://user-images.githubusercontent.com/20426972/48349706-4b1c8800-e685-11e8-816d-0c0b91e0053a.png">

I have re-ran this notebook with the Spark kernel, and it works as expected (pushed).

**Comment by yymao** [comment]
Thanks, @JulienPeloton @heather999!

Closed by https://github.com/LSSTDESC/jupyter-kernels/pull/1
