### ISSUE TITLE
Write permission for this repo

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/DC2-analysis#50]
Hi, I would like to obtain the permission for this repo to submit a notebook. However, the link to do so provided in the README is dead (https://github.com/orgs/LSSTDESC/teams/dc2-analysis-contributors/members). Could someone tell me how to do? Thanks.

**Comment by rmandelb** [comment]
Hi @marina-ricci - thanks for checking!  The link you gave is not dead; rather, it's restricted in access to DESC members who are members of the LSSTDESC GitHub organization.  From what I can see, GitHub thinks it has sent you an invitation to join the organization, but your invitation is still pending (i.e., not accepted by you) so you can't see restricted pages yet.  Do you see the invitation to join the LSSTDESC GitHub organization in your e-mail?  If not, it could have gone to spam, but you should be able to navigate to https://github.com/LSSTDESC and see your pending invitation anyway.  Once you accept, you should be able to see the page that is linked in the README.  Please try this and let me know if it works.

I can add a note to the README about the accessibility of the page to request write permission in this repo, so that it's clear that there are access restrictions.

**Comment by rmandelb** [comment]
@marina-ricci - glad this worked out!  I am closing this issue now that you have access.
