### ISSUE TITLE
Colour of cluster galaxies

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/DC2-analysis#62]
Hi all, 
I am concerned about the colour of cluster galaxies in DC2. 

I copy below an image from my notebook (#51 ), showing the rest-frame composite colour-magnitude diagram of cluster galaxies for haloes in different redshift bins. No radius cut is applied (all FoF members are included). Red dots are for centrals. 

![image](https://user-images.githubusercontent.com/45492897/50980105-37ac6280-14f8-11e9-9d3a-ededb2aa593a.png)

It seems to me that the red sequence is too much populated, especially at high redshift and faint magnitudes. Arbitrarily separating population at (u-g)_0 = 1.1 gives a red sequence fraction of > 80% in all bins.

From literature it appears that the red sequence fraction should decrease with redshift, radius and decreasing galaxy luminosity. See eg:
http://ads.nao.ac.jp/abs/2018PASJ...70S..24N
https://ui.adsabs.harvard.edu/#abs/arXiv:1604.00988
http://adsabs.harvard.edu/doi/10.1111/j.1365-2966.2007.12316.x

Do I miss something? Could someone comment on that? 
I can produce more plots if needed.

**Comment by rmandelb** [comment]
Hi @marina-ricci for some reason I'm unable to load your notebook after a few tries (perhaps some GitHub glitch), so can you please tell us which catalog version you are using for these plots?  There was some evolution from protoDC2 to cosmoDC2 in the cluster population colors, and even between sequential cosmoDC2 versions, so the exact catalog version is quite relevant to this question.

**Comment by yymao** [comment]
I think @marina-ricci is using v1.1.4 (`cosmoDC2_v1.1.4_image`) according to [this line](https://github.com/LSSTDESC/DC2-analysis/blob/u/marina-ricci/investigate_properties_of_halos_in_DC2/contributed/check_properties_of_haloes_in_CosmoDC2.ipynb?short_path=208e3ea#L66).

**Comment by marina-ricci** [comment]
Hi, my notebook is also available here: https://github.com/marina-ricci/DC2_analysis_notebooks/blob/master/investigate_properties_of_halos_in_DC2.ipynb

I used the version 'cosmoDC2_v1.1.4_small'

**Comment by rmandelb** [comment]
Thanks for the link, @marina-ricci - that one works for me.

I think that @erykoff and @j-dr provided criteria for the cluster red sequence, and iterated quite a bit with @aphearin (I get the impression that some of their tests may not be in DESCQA so I hope they can comment).  

Do I understand correctly that you are not imposing any luminosity or stellar mass cuts for the galaxies in these color-magnitude diagrams?  I do want to flag that it's possible color tests for cluster galaxies may have been defined in general based on a sample above some limiting brightness (i.e., the very faint galaxies in the highest redshift bin are not visible in the images so I'm not sure that their colors would have been carefully tuned).

**Comment by erykoff** [comment]
So I need to squint at those plots a bit more, but the cluster red-sequence validation was performed (a) at z<1.0 (which was the maximum redshift of protoDC2) and (b) for members brighter than >~0.2L*.  So anything at higher redshift than 1 and lower luminosity than 0.2L* is not something that @j-dr or I have looked at.  However, there were other color-based clustering measurements that @aphearin has done, but I don't know what redshift/luminosity those cover.

**Comment by egawiser** [comment]
If I understood correctly, the colors of red-sequence galaxies have been carefully validated, but Marina is complaining about the relative population fractions of red-sequence and "blue cloud" galaxies in clusters not evolving as a function of redshift or luminosity.  It seems possible that the latter aspect might not be one that we tested and that could join a sure-to-grow list of imperfections in our DC2 input catalog.  If it results from a too-high density of red-sequence galaxies in clusters, then our cluster-finding results would presumably end up too optimistic; if it results from a too-low density of blue-cloud galaxies in clusters, it might have less impact.

**Comment by rmandelb** [comment]
OK, I'm sorry, the plot I was thinking of *was* for massive halos rather than all galaxies (but more like groups+clusters rather than clusters only) - https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-01-07_36&test=color_z_test&right=2019-01/2019-01-07_36/color_z_test/cosmoDC2_v1.1.4_small/plot_1.png

That shows observed-frame color vs. redshift for galaxies above some brightness, and seems to suggest there is a nice narrow red sequence and an abundant blue cloud in halos above 10^13.  @marina-ricci is plotting halos above 10^14, so one immediate question would be whether the plots change significantly if you go down to 10^13 (which would suggest that it's the clusters specifically that have a deficit of blue galaxies).  Another question would be the impact of the stellar mass or other cuts.  The cuts for the plot I linked are outlined in https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-01-07_36&test=color_z_test&right=2019-01/2019-01-07_36/color_z_test/config.yaml

**Comment by marina-ricci** [comment]
Thanks for your comments. I did not apply any cut in stellar mass or magnitude. I am now trying to compute characteristic magnitude (m*) model evolution in LSST band to be easier to compare to other work. As @egawiser I am worried it might affect (boost) cluster detections with Redmapper, especially at high z. However, if it only affects faint galaxies it might not be a big issue.

**Comment by aphearin** [comment]
Thanks for the nice analysis @marina-ricci! Getting the cluster red sequence evolution correct is really important, so it's great you're looking at this in detail. 

I thought it would be useful to post a plot of the underlying analytical model for _all_ galaxies, not just cluster members. So I'm posting this here in case it's useful to talk around while we pinpoint the specific modeling feature that should be improved - this is partly motivated by the comment @rmandelb just made here. As you can see, there is very little evolution in the red fraction beyond z>1, and this plot also helps see the simultaneous dependence on galaxy brightness and redshift. 

![red_fraction_evolution](https://user-images.githubusercontent.com/6951595/50987270-c906df00-14ce-11e9-9d1c-701f72e81956.png)

**Comment by aphearin** [comment]
@j-dr - do you still have the validation plot you made of the mass-richness relation in cosmoDC2? That might also be useful to post here, since it is not in DESCQA and I don't think many people have seen it. I had pinged @erykoff about this and he said you might be the person to ask.

**Comment by marina-ricci** [comment]
@aphearin how do yo define the red sequence in your plot?
@j-dr for what it worth I have also a "richness"/FoF mass in the notebook. The richness is just based on the number of projected galaxies inside each halo (no cluster finder involved).

**Comment by aphearin** [comment]
@marina-ricci - this is a native quantity of the model that determines the hump in the double-gaussian from which broadband colors are drawn.

**Comment by marina-ricci** [comment]
The exact same plot but with all halos with with M_halo>1e13 Msol
![image](https://user-images.githubusercontent.com/45492897/50988219-35ec9a00-150c-11e9-9ac9-1acf2ef312f1.png)

**Comment by rmandelb** [comment]
@marina-ricci - Indeed it looks better with the lower halo mass cut.   So, this effect appears to depend strongly on the halo mass.

@aphearin - thanks for sharing those model plots. Let me make sure I understand some features of your model.  If I look at your z=0.5 (green) curve on the left panel, then I expect a maximal red  sequence fraction (i.e. at the highest luminosities) of 0.6.  At lower luminosities it should be more like 0.2.  I believe you were saying this model is used for all galaxies including cluster galaxies, and depends only on the variables shown on your plot, i.e, redshift and luminosity (but not other parameters such as halo mass) - is all of that correct?  

If that's correct, then I am confused about two things:

- Since @marina-ricci is plotting quantities as a function of redshift (in bins) and luminosity (on the horizontal axis), it seems to me that the red sequence fraction that we read off of of those plots should not depend on the halo mass cut that is applied, which is not the case.

- If  I look at @marina-ricci 's  plot for clusters with 0.55<z<0.65, which is the closest one to your green z=0.5 model curve, then the red sequence fraction (a) appears to be higher than the maximal value of 0.6 in your model, and (b) appears to be basically independent of luminosity, unlike the model.

I realize that I am trying to do a 1D projection of 2D plots (i.e., I'm trying to make a 1D histogram of the color at fixed luminosity) which could be going wrong, and I could be misinterpreting either your model or her plots.   Possibly there is something about the selection of halos/galaxies that isn't being factored into this discussion that makes a difference?  What are your thoughts?

**Comment by aphearin** [comment]
@rmandelb - as usual, you read everything with acuity; I didn't give enough details to fill in the rest. The plot I posted is not the entire color model. This is just the color model for galaxies "in the field", i.e., galaxies with Mhost <~10**13.5. There are several differences between the cluster red sequence and the field red sequence. The red fraction is considerably boosted in high-mass halos, and the _observer-frame_ colors of cluster red sequence galaxies has a tighter scatter, etc. I posted the above plot because I wanted to provide some reassurance that cosmoDC2 galaxies *in general* are not nearly as red as shown in the plot at the top of this thread. 

Differences in the colors of red sequence galaxies in the field vs. clusters is actually one of the primary changes to the model that we relegated to DC3 and opted not to make in DC2 due to the amount of labor involved in preserving the current tuning of the two-point functions. This issue was raised back in August and we are tracking it [here](https://github.com/LSSTDESC/cosmodc2/issues/27).

**Comment by j-dr** [comment]
Sorry to be slow replying to this. Here's the mass richness relation from cosmodc2_v0.4 (This is the latest version I have this measurement for).

![download-29](https://user-images.githubusercontent.com/5467294/51137794-4e063700-17f4-11e9-8281-d222c284279d.png)

Richness only counts galaxies brighter than 0.2L* though, so this doesn't necessarily address the concern that the red-fraction may be a bit high for very faint cluster members.

**Comment by rmandelb** [comment]
I think this cluster red fraction issue has been pretty thoroughly explored, and we now understand where it occurs and which aspects have been deferred to future work (with an open issue in the cosmoDC2 repository).  Thanks for the helpful plots, @marina-ricci @aphearin @j-dr !  

Closing #62.
